### ISSUE TITLE
Getting an error: No module named 'pycurl'

### ISSUE THREAD

**Issue by rangerrkm** [thomaspatzke/Log4Pot#14]
Hello,

Is anyone getting this error:

Pycurl not available or there is an issue with curl dependencies: No module named 'pycurl'

I tried installing pycurl for both Python2 and Python3, using these commands.

pip install pycurl

pip3 install pycurl

Both of these were already satisfied.

**Comment by thomaspatzke** [comment]
It needs some further os packages, please follow the install instructions in the readme.

**Comment by rangerrkm** [comment]
Ok, it looks like I need to re-run the poetry install command again.

Thanks,

**Comment by rangerrkm** [comment]
Thomaspatzke, I have another question, related to the config file.
I have this one working --download-dir:

But not sure how to use these two. Could you please give me an example?
--download-payloads: 
--download-class:

Thanks,

**Comment by rangerrkm** [comment]
Hi thomaspatzke,

Are these two config file options still valid? Since I do not see them in the -help, I see --download-dir, which works for me.

--download-class:

--download-dir:

Because I have one system where I do not get an error and one that gives me an error.

log4pot.py: error: unrecognized arguments: --download-class

Thanks,

**Comment by thomaspatzke** [comment]
No, I've removed them today. `--payloader` now enables the payload download and locations are configured with `--download-dir` and `--download-container`.

**Comment by rangerrkm** [comment]
Ok, good to know.
Thanks for the update.
