### ISSUE TITLE
T-Pot integration

### ISSUE THREAD

**Issue by t3chn0m4g3** [thomaspatzke/Log4Pot#6]
@thomaspatzke Great work, thank you!
Did not find a license, are you ok with [T-Pot](https://github.com/telekom-security/tpotce) integration?

**Comment by thomaspatzke** [comment]
GPL...It's well hidden in pyproject.toml 😉

I'm fine with it, go ahead!

**Comment by t3chn0m4g3** [comment]
Thank you 😃

**Comment by thomaspatzke** [comment]
Added license now.

**Comment by t3chn0m4g3** [comment]
Thx!

**Comment by t3chn0m4g3** [comment]
... and [done](https://github.com/telekom-security/tpotce/discussions/972).
